version: "3"

services:
  sgpo:
    container_name: "sgpo-web"
    build:
      context: .
    init: true
    restart: "always"
    ports:
      - "80:80"
    links:
      - banco

  banco:
    build:
      context: ./bin/mariaDB
    container_name: "sgpo-banco"
    init: true
    restart: "always"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SenhaRootBD}
      MYSQL_DATABASE: ${BD}
      MYSQL_USER: ${UserBD}
      MYSQL_PASSWORD: ${UserSenha}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "sgpo-pma"
    init: true
    restart: "always"
    links:
      - banco
    environment:
      PMA_HOST: banco
      PMA_PORT: 3306
      SenhaRootBD: ${SenhaRootBD}
      UserBD: ${UserBD}
      UserSenha: ${UserSenha}
    ports:
      - "8080:80"
