version: "3"

services:
  php:
    container_name: "${nome_projeto}-CertBot-PHP"
    build:
      context: ./bin/php
    init: true
    restart: "always"
    ports:
      - "80:80"
#      - "443:443"
    links:
     - banco
    volumes:
      - ./www:/var/www/html
#      - ./data/letsencrypt-conf/:/etc/letsencrypt/
#      - ./scripts/certbot.sh:/certbot.sh
#    command: ["/bin/sh", "/certbot.sh"]
    environment:
      PMA_PORT: 8080

  banco:
    build: 
      context: ./bin/mariaDB
    container_name: "${nome_projeto}-banco"
    init: true
    restart: "always"
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SenhaRootBD}
      MYSQL_DATABASE: ${BD}
      MYSQL_USER: ${UserBD}
      MYSQL_PASSWORD: ${UserSenha}
    

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "${nome_projeto}-phpmyadmin"
    init: true
    restart: "always"
    links:
      - banco
    environment:
      PMA_HOST: banco
      PMA_PORT: 3306
      SenhaRootBD: ${SenhaRootBD}
      UserBD: ${UserBD}
      UserSenha: ${UserSenha}
    ports:
      - "8080:80"
